go get -u github.com/jinzhu/gorm
go get -u github.com/gin-gonic/gin
go get -u github.com/jinzhu/gorm/dialects/postgres
go get -u github.com/swaggo/gin-swagger
go get -u github.com/swaggo/swag/cmd/swag
go get -u github.com/alecthomas/template
go get -u github.com/swaggo/files
go get -u github.com/swaggo/http-swagger
go get -u github.com/gin-contrib/cors
go get -u github.com/rs/cors/wrapper/gin
go get -u github.com/dgrijalva/jwt-go
go get -u github.com/stretchr/testify